<?php

namespace AppBundle\Repository;

/**
 * SearchSubjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchSubjRepository extends \Doctrine\ORM\EntityRepository
{
}
